spring:
    application:
        name: identicator
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: ${GITHUB_REGISTRATION_ID}
                        clientSecret: ${GITHUB_REGISTRATION_SECRET}
                    google:
                        clientId: ${GOOGLE_CLIENT_ID}
                        clientSecret: ${GOOGLE_CLIENT_SECRET}
server:
    port: 8080
springdoc:
    swagger-ui:
        path: /swagger-ui.html